name: HidePlayerFromWorld
main: fr.lockface.hideplayerfromworld.HidePlayerFromWorld
depend: []
version: 1.0.0
api-version: 1.8
commands:
   hideplayerfromworld:
      description: Access to config file and admin commands
      aliases:
      - hpw
      - hpfw
      permission: hpw.command
      permission-message: You are not allowed to do that!
      usage: "/<command> [addworld|removeworld|list|showplayers|bevisible]"
permissions:
   hpw.command:
      description: Allow you to use the /hpw command
      default: op
   hpw.admin:
      description: Allow you to manage hidden worlds configs
      default: op
   hpw.seeplayers:
      description: Allow you to see players using the command /hpw seeplayers
      default: op
   hpw.bevisible:
      description: Allow you to become visible in hidden worlds using the command /hpw makevisible
      default: op
      